"""Backgrounds for levels 2 to 6 from the five supplied images (source/bg1..5.jpg), plus generated ground and foreground strips.
Each theme = sky (the image, mirror-tiled so the repeat has no seam, parallax 0.1), ground (row 191 surface like the main game) and fringe.
Writes web/assets/bgs/<name>_*.png and web/assets/bgs.js (merged into BIBOO.themes). Run: python3 build_bgs.py"""
import os, sys, json, random
from PIL import Image, ImageDraw
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, '..', 'arenas'))
import build_arenas as A
OUT = os.path.join(HERE, '..', '..', 'web', 'assets')
W, H, GY = 384, 232, 191
def pat_blue(d, r):
    for row, y in enumerate(range(GY + 6, H, 11)):
        for x in range(-(row % 2) * 14, W, 28): d.rectangle([x, y, x + 26, y + 9], outline=(20, 30, 70, 255)); d.line([x + 1, y + 1, x + 24, y + 1], fill=(70, 100, 170, 255))
def pat_dirt(d, r):
    for _ in range(120):
        x, y = r.randrange(W), r.randrange(GY + 7, H - 2); d.rectangle([x, y, x + r.randrange(3, 9), y + 1], fill=r.choice([(150, 100, 70, 255), (96, 64, 46, 255), (190, 140, 96, 255)]))
# name: (source, crop box x0,y0,x1,y1 (ground line = y1), palette top/mid/deep/lip, pattern, fringe kind)
T = {
 'falls':   (1, (0, 0, 750, 308),   ('#5a8a3a', '#3e4a3a', '#222c2a', '#2c4a26'), A.pat_moss, 'fungus'),
 'canyon':  (2, (0, 0, 800, 606),   ('#9ab04c', '#7a5a3a', '#4a3626', '#c88a5a'), pat_dirt, 'bone'),
 'shore':   (3, (28, 30, 644, 338), ('#e8d09a', '#c8a870', '#6a5a48', '#9ac0c0'), A.pat_wet, 'bone'),
 'mire':    (4, (820, 0, 1920, 790), ('#6a7a3a', '#3a3426', '#241e18', '#4a5a2a'), A.pat_moss, 'fungus'),
 'sanctum': (5, (0, 0, 1093, 500),  ('#3a5a9a', '#1c2a52', '#10183a', '#5a7ac0'), pat_blue, 'crypt'),
}
def layer(src, box):
    im = Image.open(os.path.join(HERE, 'source', f'bg{src}.jpg')).convert('RGB').crop(box)
    k = (GY + 6) / im.height                                            # the source's ground line lands just under the game's ground line
    im = im.resize((max(1, round(im.width * k)), GY + 6), Image.LANCZOS)
    im = im.quantize(colors=96, method=Image.MEDIANCUT, dither=Image.NONE).convert('RGB')
    w = im.width
    out = Image.new('RGB', (w * 2, H), im.getpixel((0, im.height - 1)))
    out.paste(im, (0, 0)); out.paste(im.transpose(Image.FLIP_LEFT_RIGHT), (w, 0))      # mirrored copy: no seam where it repeats
    bottom = im.crop((0, im.height - 1, w, im.height)).resize((w, H - im.height))
    out.paste(bottom, (0, im.height)); out.paste(bottom.transpose(Image.FLIP_LEFT_RIGHT), (w, im.height))
    return out.convert('RGBA')
if __name__ == '__main__':
    os.makedirs(os.path.join(OUT, 'bgs'), exist_ok=True)
    out = {}
    for n, (src, box, pal, pat, fr) in T.items():
        layer(src, box).save(os.path.join(OUT, 'bgs', f'{n}_sky.png'), optimize=True)
        A.ground(n, *pal, pat, 40 + src).save(os.path.join(OUT, 'bgs', f'{n}_ground.png'), optimize=True)
        A.fringe(fr, src).save(os.path.join(OUT, 'bgs', f'{n}_fringe.png'), optimize=True)
        out[n] = {'layers': [{'src': f'assets/bgs/{n}_sky.png', 'parallax': 0.12, 'shake': 0.3}, {'src': f'assets/bgs/{n}_ground.png', 'parallax': 1.0, 'shake': 1.0}], 'fringe': f'assets/bgs/{n}_fringe.png'}
    open(os.path.join(OUT, 'bgs.js'), 'w').write('// generated by tools/backgrounds/build_bgs.py\nwindow.BIBOO.themes = Object.assign(window.BIBOO.themes || {}, ' + json.dumps(out, separators=(',', ':')) + ');\n')
    print('ok')
