#!/usr/bin/env python3
"""Bake the Green Trail and Perry's idle at 1:1 (not the Dreamcast's 5/6) into a PPK1 pack.

The sprite bytes are the same format as ports/dreamcast/tools/bake_game.py, so the blitter
can draw either. This pack is only the boot screen. The move and enemy tables stay in the
web game until the 68000 runtime can take them without floats.

    python3 ports/mame2003/tools/bake_art.py
"""
import json
import os
import subprocess
import sys

import numpy as np
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
PORT = os.path.dirname(HERE)
ROOT = os.path.dirname(os.path.dirname(PORT))
WEB = os.path.join(ROOT, "web")
sys.path.insert(0, os.path.join(ROOT, "ports", "dreamcast", "tools"))
import bake_game as bg  # noqa: E402

JSON = os.path.join(PORT, "build", "game_data.json")
ART = os.path.join(PORT, "roms", "art.bin")
HDR = os.path.join(PORT, "game", "art_ids.h")
VIEW_SCALE = 1.0
CHAR_SCALE = 0.5  # sheet pixels to view pixels, the web game's SPRITE_SCALE

LIGHTS = {
    "trail": ("#1c140c", 0.28),
}


def grade(rgba, key, row0, view_h):
    col, ga = LIGHTS.get(key, LIGHTS["trail"])
    c = np.array([int(col[i:i + 2], 16) for i in (1, 3, 5)], float) / 255.0
    out = rgba.astype(float)
    h = rgba.shape[0]
    for r in range(h):
        t = min(1.0, max(0.0, (r + row0) / float(view_h)))
        k = t / 0.55 if t <= 0.55 else (1.0 - t) / 0.45
        src = c + (1.0 - c) * k
        out[r, :, :3] *= (1.0 - ga + ga * src)
    return np.clip(out + 0.5, 0, 255).astype(np.uint8)


def c_list(name, rows, n):
    body = ",".join(str(int(v)) for v in rows)
    return f"static const unsigned short {name}[{n}] = {{{body}}};"


def main():
    os.makedirs(os.path.dirname(JSON), exist_ok=True)
    os.makedirs(os.path.dirname(ART), exist_ok=True)
    if not os.path.exists(JSON):
        subprocess.check_call(["node", os.path.join(HERE, "dump_boot.cjs"), JSON])
    D = json.load(open(JSON))
    v = D["view"]
    pack = bg.Pack()
    margin = int(v["margin"])

    layer_ids, periods, pars, margins = [], [], [], []
    for layer in D["layers"]:
        im = np.asarray(Image.open(os.path.join(WEB, layer["src"])).convert("RGBA"))
        im = grade(im, "trail", -margin, v["h"])
        o, ox, oy = bg.sample(im, 0, 0, im.shape[1], im.shape[0], 0, 0, VIEW_SCALE)
        layer_ids.append(pack.add("layer:" + layer["src"], bg.encode(o, ox, oy)))
        periods.append(im.shape[1])
        pars.append(int(round(float(layer["parallax"]) * 256)))
        margins.append(margin)

    fr = np.asarray(Image.open(os.path.join(WEB, D["fringe"]["src"])).convert("RGBA"))
    o, ox, oy = bg.sample(fr, 0, 0, fr.shape[1], fr.shape[0], 0, 0, VIEW_SCALE)
    fringe = pack.add("fringe", bg.encode(o, ox, oy))
    fringe_period = int(fr.shape[1])

    idle = D["moves"]["idle"]
    # The basic kit from the web pad, after 00_core.js. Roots stay whole pixels.
    # walk_left is not baked: the game flips walk_right. Charge, beams and supers stay out.
    KIT = [
        ("IDLE", "idle", "IDLE"),
        ("WALK", "walk_right", "WALK"),
        ("DUCK", "duck", "DUCK"),
        ("BLOCK", "block", "BLOCK"),
        ("PARRY", "parry", "PARRY"),
        ("SLASH", "slash", "SLASH"),
        ("DASH", "dash", "DASH"),
        ("JUMP", "jump", "JUMP"),
        ("SPIN", "spin_attack", "SPIN"),
        ("THRUST", "thrust", "THRUST"),
        ("UPSWING", "upswing", "SWING"),
    ]
    f_ms, f_spr, f_rx, f_ry = [], [], [], []
    mv_f0, mv_n, mv_loop, mv_lf = [], [], [], []
    for enum, key, _label in KIT:
        m = D["moves"][key]
        cw, ch = m["cell"]
        ax, ay = m["anchor"]
        sheet = np.asarray(Image.open(os.path.join(WEB, m["sheet"])).convert("RGBA"))
        mv_f0.append(len(f_ms))
        nfr = 0
        for k, f in enumerate(m["frames"]):
            o, ox, oy = bg.sample(sheet, k * cw, 0, cw, ch, ax, ay, CHAR_SCALE)
            sid = pack.add(f"{key}:{k}", bg.encode(o, ox, oy))
            if sid < 0:
                sys.exit(f"empty frame {key}:{k}")
            f_ms.append(int(f["ms"]))
            f_spr.append(sid)
            f_rx.append(int(round(float(f["root"][0]))))
            f_ry.append(int(round(float(f["root"][1]))))
            nfr += 1
        mv_n.append(nfr)
        mv_loop.append(1 if m.get("loop") else 0)
        mv_lf.append(int(m.get("loopFrom") or 0))
        print(f"  {key}: {nfr} frames")

    size = pack.write(ART)
    n = len(layer_ids)
    nf = len(f_ms)
    nm = len(KIT)
    lines = [
        "/* generated by tools/bake_art.py, do not edit */",
        "#ifndef ART_IDS_H",
        "#define ART_IDS_H",
        f"#define VIEW_W {int(v['w'])}",
        f"#define VIEW_H {int(v['h'])}",
        f"#define VIEW_MARGIN {margin}",
        f"#define ANCHOR_X {int(v['anchorX'])}",
        f"#define FEET_ROW {int(v['feetRow'])}",
        f"#define NLAYERS {n}",
        c_list("LAYER_ID", layer_ids, n),
        c_list("LAYER_PERIOD", periods, n),
        c_list("LAYER_PAR", pars, n),
        c_list("LAYER_MARGIN", margins, n),
        f"#define FRINGE_ID {int(fringe)}",
        f"#define FRINGE_PERIOD {fringe_period}",
        "enum { " + ", ".join(f"MV_{a}" for a, _, _ in KIT) + ", MV_COUNT };",
        f"#define NFRAMES {nf}",
        c_list("F_MS", f_ms, nf),
        c_list("F_SPR", f_spr, nf),
        "static const short F_RX[NFRAMES] = {" + ",".join(str(int(x)) for x in f_rx) + "};",
        "static const short F_RY[NFRAMES] = {" + ",".join(str(int(y)) for y in f_ry) + "};",
        c_list("MV_F0", mv_f0, nm),
        c_list("MV_N", mv_n, nm),
        c_list("MV_LOOP", mv_loop, nm),
        c_list("MV_LF", mv_lf, nm),
        "static const char *const MV_NAME[MV_COUNT] = {" + ",".join(f'"{lab}"' for _, _, lab in KIT) + "};",
        "#endif",
        "",
    ]
    with open(HDR, "w") as f:
        f.write("\n".join(lines))
    print(f"art.bin {size} bytes, {len(pack.blobs)} sprites, {nf} move frames")
    print(f"wrote {HDR}")


if __name__ == "__main__":
    main()
