#!/usr/bin/env python3
"""Pad the boot image to 512K, zip it as parryperry.zip, write the MAME hash line."""
import hashlib
import sys
import zlib
import zipfile
from pathlib import Path

SIZE = 0x80000


def main() -> None:
    if len(sys.argv) != 5:
        sys.exit("usage: pack_rom.py UNPADDED BIN ZIP ROM_LOAD_INC")
    raw = Path(sys.argv[1]).read_bytes()
    if len(raw) > SIZE:
        sys.exit(f"image is {len(raw)} bytes, the ROM slot is {SIZE}")
    if raw[:4] != b"\x00\x11\x00\x00":
        sys.exit(f"reset SP is {raw[:4].hex()}, expected 00110000")
    image = raw + bytes(SIZE - len(raw))
    crc = zlib.crc32(image) & 0xFFFFFFFF
    sha = hashlib.sha1(image).hexdigest()
    out_bin = Path(sys.argv[2])
    out_zip = Path(sys.argv[3])
    inc = Path(sys.argv[4])
    out_bin.parent.mkdir(parents=True, exist_ok=True)
    out_bin.write_bytes(image)
    with zipfile.ZipFile(out_zip, "w", compression=zipfile.ZIP_DEFLATED) as z:
        z.write(out_bin, "main.bin")
    inc.write_text(
        "/* generated by tools/pack_rom.py, do not edit */\n"
        f"ROM_LOAD16_WORD(\"main.bin\", 0x000000, 0x00080000, CRC({crc:08x}) SHA1({sha}))\n"
    )
    print(f"main.bin {SIZE} bytes  crc {crc:08x}  sha1 {sha}")
    print(f"zip {out_zip}  ({out_zip.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
