#!/usr/bin/env python3
"""Pad the program to 512K, zip it with the art pack, write the MAME ROM lines."""
import hashlib
import sys
import zlib
import zipfile
from pathlib import Path

PROG = 0x80000
ART_AT = 0x80000


def digest(data: bytes):
    return zlib.crc32(data) & 0xFFFFFFFF, hashlib.sha1(data).hexdigest()


def main() -> None:
    if len(sys.argv) != 6:
        sys.exit("usage: pack_rom.py UNPADDED ART BIN ZIP ROM_LOAD_INC")
    raw = Path(sys.argv[1]).read_bytes()
    art = Path(sys.argv[2]).read_bytes()
    if len(raw) > PROG:
        sys.exit(f"program is {len(raw)} bytes, the slot is {PROG}")
    if raw[:4] != b"\x00\x11\x00\x00":
        sys.exit(f"reset SP is {raw[:4].hex()}, expected 00110000")
    if art[:4] != b"PPK1":
        sys.exit("art.bin does not start with PPK1")
    image = raw + bytes(PROG - len(raw))
    crc, sha = digest(image)
    acrc, asha = digest(art)
    region = ART_AT + len(art)
    if region & 1:
        region += 1
    out_bin = Path(sys.argv[3])
    out_zip = Path(sys.argv[4])
    inc = Path(sys.argv[5])
    out_bin.parent.mkdir(parents=True, exist_ok=True)
    out_bin.write_bytes(image)
    with zipfile.ZipFile(out_zip, "w", compression=zipfile.ZIP_DEFLATED) as z:
        z.write(out_bin, "main.bin")
        z.write(sys.argv[2], "art.bin")
    inc.write_text(
        "/* generated by tools/pack_rom.py, do not edit */\n"
        f"ROM_REGION(0x{region:x}, REGION_CPU1, 0)\n"
        f"ROM_LOAD16_WORD(\"main.bin\", 0x000000, 0x00080000, CRC({crc:08x}) SHA1({sha}))\n"
        f"ROM_LOAD(\"art.bin\", 0x00080000, 0x{len(art):x}, CRC({acrc:08x}) SHA1({asha}))\n"
    )
    print(f"main.bin {PROG} bytes  crc {crc:08x}")
    print(f"art.bin {len(art)} bytes  crc {acrc:08x}")
    print(f"zip {out_zip}  ({out_zip.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
