/* Items menu name, Y descriptions, no leaves over pits. Run: NODE_PATH=$(npm root -g) node web/tests/menus_info.test.js */
const path = require('path');
const { chromium } = require('playwright');
const LV = require('../levels.js');
(async () => {
  const res = [], check = (n, ok, d) => { res.push(ok); console.log(`${ok ? 'PASS' : 'FAIL'}  ${n}${ok ? '' : '  ' + JSON.stringify(d)}`); };
  let bad = 0;
  for (const L of LV.levels) for (const m of L.maps) for (const l of m.leaves) if (m.pits.some(q => l.x > q.x0 - 8 && l.x < q.x1 + 8)) bad++;
  check('no leaf sits over a pit on any map', bad === 0, bad);
  const b = await chromium.launch(), page = await b.newPage({ viewport: { width: 1200, height: 900 } });
  const errors = []; page.on('pageerror', e => errors.push(String(e)));
  await page.goto('file://' + path.resolve(__dirname, '../index.html'));
  await page.waitForFunction(() => document.getElementById('btn-start') && window.bibooGame, null, { timeout: 20000 });
  const ev = j => page.evaluate(j), wait = ms => page.waitForTimeout(ms);
  await ev('bibooGame.resetAll()');
  await page.locator('#menu-view button', { hasText: /^Items$/ }).click(); await wait(200);
  check('the sub menu is titled Items', (await ev("document.getElementById('menu-title').textContent")) === 'Items');
  check('Y shows nothing yet', /Y:/.test(await ev("document.getElementById('info-box').textContent")));
  await ev('BibooUI.info()');
  const t1 = await ev("document.getElementById('info-box').textContent");
  check('Y describes the first item (a Bone)', /Bone/.test(t1), t1);
  await ev('BibooUI.nav(1)');
  const t2 = await ev("document.getElementById('info-box').textContent");
  check('moving down describes the next item (Quartz), even though its Use is greyed out', /Quartz/.test(t2), t2);
  await ev('BibooUI.info()');
  check('Y again hides it', /Y:/.test(await ev("document.getElementById('info-box').textContent")));
  await ev("BibooUI.open('moves', { device: 'pad' })"); await wait(150);
  await ev('BibooUI.info()');
  const t3 = await ev("document.getElementById('info-box').textContent");
  check('Y over a move in the Moves menu gives a description', t3.length > 20 && /How:/.test(t3), t3);
  await ev('BibooUI.nav(1)');
  check('the cursor row is marked', (await ev("document.querySelectorAll('#menu-view tr.cur').length")) === 1);
  await ev("bibooGame.state(); BibooUI.open('shop', { back: () => {} })"); await wait(150);
  await ev('BibooUI.info()');
  const t4 = await ev("document.getElementById('info-box').textContent");
  check('Y in the shop describes the highlighted row', t4.length > 20 && t4 !== 'Nothing to describe here.', t4);
  for (let i = 0; i < 6; i++) await ev('BibooUI.nav(1)');
  const t5 = await ev("document.getElementById('info-box').textContent");
  check('and an unlockable row too', /Mutagen|Scroll|How:/.test(t5), t5);
  check('no page errors', !errors.length, errors);
  await b.close(); process.exit(res.every(Boolean) ? 0 : 1);
})();
