"""Extra moves for the chain unlocks, built by recombining frames of Max's existing sheets (rotated, shifted, re-timed).
Writes web/assets/moves_extra/<id>.png and web/assets/moves_extra.js (adds to BIBOO.moves). The chain moves are only
reachable through the A mash (see `chainStep` in web/game.js); they carry no knockback (it is keyed by move id in game.js).
Run: python3 build_moves.py"""
import json, os, copy
from PIL import Image
HERE = os.path.dirname(os.path.abspath(__file__))
WEB = os.path.join(HERE, '..', '..', 'web')
CW, CH, AX, AY = 300, 200, 110, 196
D = json.loads((lambda s: s[s.index('=') + 1:].rstrip().rstrip(';'))(open(os.path.join(WEB, 'assets', 'data.js')).read()))['moves']
# frame: (source move, source frame, ms, dx sheet px (forward +), dy sheet px (up +), rotation deg (+ = lean back, counter-clockwise), root override or None, keep hits)
MOVES = {
 'chain2': ('Rising cut', [
     ('slash', 1, 50, -8, 0, 4, None, False),
     ('upswing', 2, 60, 6, 0, 0, None, True),
     ('upswing', 3, 70, 10, 0, 0, None, True),
     ('slash', 3, 60, 0, 0, 0, [8, 0], True),
     ('slash', 4, 60, 0, 0, 0, [8, 0], False)]),
 'chain3': ('Spin thrust', [
     ('spin_attack', 0, 50, 0, 0, 0, None, False),
     ('spin_attack', 1, 45, 0, 0, 0, None, True),
     ('spin_attack', 2, 45, 0, 0, 0, None, True),
     ('thrust', 2, 60, 0, 0, 0, [14, 0], True),
     ('thrust', 3, 60, 0, 0, 0, [18, 0], True),
     ('thrust', 4, 60, 0, 0, 0, [18, 0], False)]),
 'chain4': ('Crescent dance', [
     ('thrust', 1, 50, 0, 0, 3, [6, 0], False),
     ('slash', 2, 55, 4, 0, -4, [12, 10], True),
     ('upswing', 2, 55, 6, 0, 0, [18, 16], True),
     ('spin_attack', 4, 60, 4, 0, 0, [18, 12], True),
     ('slash', 3, 55, 0, 0, 0, [18, 0], True),
     ('slash', 4, 70, 0, 0, 0, [18, 0], False)]),
}
def shift_hits(hits, dx, dy):
    out = []
    for h in copy.deepcopy(hits or []):
        for key in ('a', 'b', 'c'):
            if key in h: h[key] = [round(h[key][0] + dx, 1), round(h[key][1] + dy, 1)]
        out.append(h)
    return out
def build():
    extra = {}
    for mid, (title, fr) in MOVES.items():
        cells, frames = [], []
        for (src, k, ms, dx, dy, rot, root, keep) in fr:
            m = D[src]; cw, ch = m['cell']; ax, ay = m['anchor']; f = m['frames'][k]
            sheet = Image.open(os.path.join(WEB, m['sheet'])).convert('RGBA')
            c = sheet.crop((k * cw, 0, k * cw + cw, ch))
            out = Image.new('RGBA', (CW, CH), (0, 0, 0, 0)); out.alpha_composite(c, (AX + dx - ax, AY - dy - ay))
            if rot: out = out.rotate(rot, resample=Image.NEAREST, center=(AX + dx, AY - dy))
            cells.append(out)
            r = root if root is not None else f['root']
            frames.append({'name': f"{src}{k}", 'ms': ms, 'root': [float(r[0]), float(r[1])], 'shake': [0, 0], 'bw': None,
                           'hits': shift_hits(f['hits'], dx, dy) if keep and f['hits'] else None, 'top': f.get('top', 80) + dy})
        sheet = Image.new('RGBA', (CW * len(cells), CH), (0, 0, 0, 0))
        for i, c in enumerate(cells): sheet.paste(c, (i * CW, 0))
        sheet.save(os.path.join(WEB, 'assets', 'moves_extra', f'{mid}.png'), optimize=True)
        extra[mid] = {'title': title, 'input': 'A x5', 'loop': False, 'loopFrom': 0, 'inputType': 'press', 'sheet': f'assets/moves_extra/{mid}.png', 'cell': [CW, CH], 'anchor': [AX, AY], 'aftershake': None, 'enter': None, 'frames': frames}
    return extra
if __name__ == '__main__':
    open(os.path.join(WEB, 'assets', 'moves_extra.js'), 'w').write('// generated by tools/moves_extra/build_moves.py\nObject.assign(window.BIBOO.moves, ' + json.dumps(build(), separators=(',', ':')) + ');\n')
    print('ok')
