/* generated by tools/bake_art.py, do not edit */
#ifndef ART_IDS_H
#define ART_IDS_H
#define VIEW_W 384
#define VIEW_H 216
#define VIEW_MARGIN 8
#define ANCHOR_X 96
#define FEET_ROW 188
#define NLAYERS 6
static const unsigned short LAYER_ID[6] = {0,1,2,3,4,5};
static const unsigned short LAYER_PERIOD[6] = {384,384,384,384,384,384};
static const unsigned short LAYER_PAR[6] = {26,51,90,141,179,256};
static const unsigned short LAYER_MARGIN[6] = {8,8,8,8,8,8};
#define FRINGE_ID 6
#define FRINGE_PERIOD 384
#define IDLE_N 4
static const unsigned short IDLE_ID[4] = {7,8,9,10};
static const unsigned short IDLE_MS[4] = {360,240,300,240};
#endif
