"""Sunset Training assets: the heavy bag and Slime Bunny, cleaned from the supplied stills in source/.
Writes web/assets/training/bag.png, bunny.png and web/assets/training.js (adds BIBOO.enemies.heavybag and BIBOO.training).
Sheets are drawn at 2x world size (SPRITE_SCALE is 0.5). Run: python3 build.py (from tools/training)"""
import json, os
from PIL import Image, ImageDraw
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, '..', '..', 'web', 'assets')

def clean(name, bg, thresh):
    im = Image.open(os.path.join(HERE, 'source', name)).convert('RGBA')
    marker = (255, 0, 255, 0)
    for pt in [(0, 0), (im.width - 1, 0), (0, im.height - 1), (im.width - 1, im.height - 1)]:
        if im.getpixel(pt)[3]: ImageDraw.floodfill(im, pt, marker, thresh=thresh)
    px = im.load()
    for y in range(im.height):                                          # the flood leaves colour in transparent pixels: zero them
        for x in range(im.width):
            if px[x, y][3] == 0: px[x, y] = (0, 0, 0, 0)
    return im.crop(im.getbbox())

def fit(im, h):                                                        # scale to h px tall, crisp: box filter then a small palette, hard alpha
    w = max(1, round(im.width * h / im.height))
    a = im.resize((w, h), Image.BOX)
    alpha = a.getchannel('A').point(lambda v: 255 if v > 110 else 0)
    rgb = a.convert('RGB').quantize(colors=28, method=Image.MEDIANCUT, dither=Image.NONE).convert('RGB')
    out = rgb.convert('RGBA'); out.putalpha(alpha)
    return out

def sheet(im, pad=4):
    w, h = im.width + pad * 2, im.height + pad * 2
    cell = Image.new('RGBA', (w, h), (0, 0, 0, 0)); cell.paste(im, (pad, pad), im)
    return cell

if __name__ == '__main__':
    os.makedirs(os.path.join(OUT, 'training'), exist_ok=True)
    bag = sheet(fit(clean('bag.webp', None, 14), 100))
    bunny = sheet(fit(clean('bunny.webp', None, 10), 52))
    bag.save(os.path.join(OUT, 'training', 'bag.png'), optimize=True)
    bunny.save(os.path.join(OUT, 'training', 'bunny.png'), optimize=True)
    bw, bh = bag.size
    enemy = {'title': 'Heavy bag', 'sheet': 'assets/training/bag.png', 'cell': [bw, bh], 'anchor': [bw // 2, bh],
             'frames': [{'src': 0, 'ms': 200, 'hurt': [-bw // 2 + 6, 0, bw // 2 - 6, bh - 6], 'hit': None, 'ground': 0}],
             'anims': {'idle': {'frames': [0], 'loop': True}},
             'ai': {'speed': 0, 'reach': 0, 'attacks': [], 'rest': [1000, 1000], 'knock': [0, 0], 'parried': [0, 0], 'hp': 1000000, 'dmg': 0, 'atk': {}, 'prop': True}}
    uw, uh = bunny.size
    tr = {'bunny': {'sheet': 'assets/training/bunny.png', 'cell': [uw, uh], 'anchor': [uw // 2, uh]}}
    open(os.path.join(OUT, 'training.js'), 'w').write('// generated by tools/training/build.py\nwindow.BIBOO.enemies = Object.assign(window.BIBOO.enemies || {}, ' + json.dumps({'heavybag': enemy}, separators=(',', ':')) + ');\nwindow.BIBOO.training = ' + json.dumps(tr, separators=(',', ':')) + ';\n')
    print('ok', bag.size, bunny.size)
