#!/usr/bin/env python3
"""Bake the Parry Perry soundtrack for the Dreamcast sound chip. ON-DEMAND tool (see ../README.md).

The web soundtrack is generated by tools/music/compose.py (two pulse voices and an arpeggio, a triangle bass and a drum set, from a
seeded rule set), so the notes exist as data before they are rendered to audio. This script runs compose() for every song and writes the
note events, quantised to 60 Hz frames, as C tables for src/audio.c, which plays them on AICA voices.

    python3 ports/dreamcast/tools/bake_music.py            # -> src/gen/music_data.h and src/gen/music_data.c

compose.py imports mido only to write .mid files, which this script never does, so a stub module stands in for it.
"""
import importlib.util
import math
import os
import sys
import types

HERE = os.path.dirname(os.path.abspath(__file__))
PORT = os.path.dirname(HERE)
ROOT = os.path.dirname(os.path.dirname(PORT))
GEN = os.path.join(PORT, 'src', 'gen')

sys.modules.setdefault('mido', types.ModuleType('mido'))
spec = importlib.util.spec_from_file_location('compose', os.path.join(ROOT, 'tools', 'music', 'compose.py'))
compose = importlib.util.module_from_spec(spec)
spec.loader.exec_module(compose)

FPS = 60.0
# voices: 0 lead, 1 harmony, 2 arpeggio, 3 bass, 4 kick, 5 snare or hat (the noise voice)
VOICE_OF = {'lead': 0, 'harm': 1, 'arp': 2, 'bass': 3}
# the web mix (compose.py render): lead .20, harm .11, arp .09, bass .32, kick .45, snare .30, hat .13 of full scale
AMP = {0: .20, 1: .11, 2: .09, 3: .32, 4: .45, 5: .30}
GLOBAL = 0.5


def reg_for_rate(rate):
    """AICA pitch register for a sample rate: rate = 44100 * 2^OCT * (1 + FNS / 1024), OCT a 4 bit signed number"""
    octv = math.floor(math.log2(rate / 44100.0))
    octv = max(-8, min(7, octv))
    fns = int(round((rate / 44100.0 / 2 ** octv - 1.0) * 1024))
    if fns >= 1024:
        fns, octv = 0, octv + 1
    return ((octv & 0xf) << 11) | max(0, min(1023, fns))


def main():
    os.makedirs(GEN, exist_ok=True)
    H = ['/* GENERATED by ports/dreamcast/tools/bake_music.py from tools/music/compose.py. Do not edit by hand. */',
         '#ifndef MUSIC_DATA_H\n#define MUSIC_DATA_H',
         'typedef struct { unsigned short frame; unsigned char voice, note, vel, dur; } MusicEvent;     /* dur in frames */',
         'typedef struct { const char *id; const MusicEvent *ev; unsigned short nev, frames, duty; } Track;   /* duty: pulse waveform of the lead, 0 12.5%, 1 25%, 2 50% */']
    C = ['/* GENERATED by ports/dreamcast/tools/bake_music.py from tools/music/compose.py. Do not edit by hand. */', '#include "music_data.h"']
    ids = list(compose.SONGS)
    rows = []
    for sid in ids:
        sp = dict(compose.SONGS[sid])
        ev, total_steps, step = compose.compose(sp)
        spf = step * FPS                                           # frames per sixteenth step
        out = []
        for name, voice in VOICE_OF.items():
            for st, dur, m, vel in ev[name]:
                out.append((int(round(st * spf)), voice, m, vel, max(1, min(255, int(round(dur * spf))))))
        for st, dur, m, vel in ev['drum']:
            out.append((int(round(st * spf)), 4 if m == 36 else 5, m, vel, 1))          # note 36 kick, 38 snare, 42 hat
        out.sort(key=lambda e: (e[0], e[1]))
        total = int(round(total_steps * spf))
        if total > 65535 or any(e[0] > 65535 for e in out):
            sys.exit(f'{sid} is too long for 16 bit frame numbers')
        C.append('static const MusicEvent EV_%s[%d] = {' % (sid.upper(), len(out)) + ','.join('{%d,%d,%d,%d,%d}' % e for e in out) + '};')
        duty = {.125: 0, .25: 1, .5: 2}[sp['duty']]
        rows.append('{"%s",EV_%s,%d,%d,%d}' % (sid, sid.upper(), len(out), total, duty))
        print(sid, len(out), 'events', total, 'frames', round(total / FPS, 1), 's')
    H.append('enum { ' + ', '.join('TRK_' + s.upper() for s in ids) + ', TRK_COUNT };')
    H.append('extern const Track TRACKS[TRK_COUNT];')
    C.append('const Track TRACKS[TRK_COUNT] = {' + ','.join(rows) + '};')
    # pitch registers for a 32 sample waveform looping at note * 32 Hz, for every MIDI note, the kick glide, and the noise rates
    H.append('extern const unsigned short NOTE_REG[128];')
    C.append('const unsigned short NOTE_REG[128] = {' + ','.join(str(reg_for_rate(compose.mtof(n) * 32)) for n in range(128)) + '};')
    kick = [150 * math.exp(-(i / FPS) * 28) + 42 for i in range(10)]                 # the web kick: a sine gliding down from 190 Hz to 42 Hz
    H.append('extern const unsigned short KICK_REG[10];\nextern const unsigned short NOISE_SNARE_REG, NOISE_HAT_REG;')
    C.append('const unsigned short KICK_REG[10] = {' + ','.join(str(reg_for_rate(f * 32)) for f in kick) + '};')
    C.append('const unsigned short NOISE_SNARE_REG = %d, NOISE_HAT_REG = %d;' % (reg_for_rate(9000), reg_for_rate(16000)))
    # total level (attenuation, 0.375 dB per step) for an amplitude 0..255
    tl = []
    for a in range(256):
        tl.append(255 if a == 0 else max(0, min(255, int(round(-20 * math.log10(a / 255.0) / 0.375)))))
    H.append('extern const unsigned char TL_OF_AMP[256];')
    C.append('const unsigned char TL_OF_AMP[256] = {' + ','.join(map(str, tl)) + '};')
    H.append('extern const unsigned char VOICE_AMP[6];                     /* base amplitude 0..255 of each voice before velocity and envelope */')
    C.append('const unsigned char VOICE_AMP[6] = {' + ','.join(str(int(round(AMP[v] * GLOBAL * 255 / .45))) for v in range(6)) + '};')
    H.append('#endif')
    open(os.path.join(GEN, 'music_data.h'), 'w').write('\n'.join(H) + '\n')
    open(os.path.join(GEN, 'music_data.c'), 'w').write('\n'.join(C) + '\n')
    print('wrote', os.path.join(GEN, 'music_data.c'))


if __name__ == '__main__':
    main()
