/* Parry Perry — load base game and apply local patches */
(async function () {
  const res = await fetch('https://cdn.jsdelivr.net/gh/xenodorian/Biboo@4b0432e5c13bb7f13f627f8064409f230484b72a/web/game.js');
  if (!res.ok) throw new Error('failed to load base game');
  let src = await res.text();
  src = src.replace("  const D = window.BIBOO;\n  const V = D.view;\n  const canvas = document.getElementById('view');\n  const g = canvas.getContext('2d');\n  g.imageSmoothingEnabled = false;", "  const D = window.BIBOO;\n  D.input.sequence_window_ms = 700;\n  if (!D.input.bindings.some(b => b.input === 'Left-Right+A')) D.input.bindings.push({ input: 'Left-Right+A', type: 'sequence', move: 'beam_cloud' });\n  const V = D.view;\n  const SPRITE_SCALE = 0.5;\n  const canvas = document.getElementById('view');\n  const g = canvas.getContext('2d');\n  g.imageSmoothingEnabled = false;");
  src = src.replace("                   dash_thrust: 22, energy_dash_thrust: 35, spin_attack: 20, energy_wave: 40, earthquake: 30, meteor_shower: 25 };", "                   dash_thrust: 22, energy_dash_thrust: 35, spin_attack: 20, energy_wave: 40, earthquake: 250, meteor_shower: 200 };");
  src = src.replace("  const BEAM_LEN = 330, BEAM_GROW = 3, BEAM_SPEED = 0.45, BEAM_TICK = 100, BEAM_CORE = 0.7;", "  const BEAM_LEN = 500, BEAM_GROW = 8, BEAM_SPEED = 0.45, BEAM_TICK = 100, BEAM_CORE = 0.7;");
  src = src.replace("  function blit(im, sx, w, h, dx, dy, tc) {\n    if (!tc) { g.drawImage(im, sx, 0, w, h, dx, dy, w, h); return; }\n    if (wash.width < w || wash.height < h) { wash.width = Math.max(wash.width, w); wash.height = Math.max(wash.height, h); }\n    wg.globalCompositeOperation = 'source-over'; wg.globalAlpha = 1;\n    wg.clearRect(0, 0, wash.width, wash.height);\n    wg.drawImage(im, sx, 0, w, h, 0, 0, w, h);\n    wg.globalCompositeOperation = 'source-atop'; wg.globalAlpha = tc.alpha || 0.7;\n    wg.fillStyle = tc.color; wg.fillRect(0, 0, w, h);\n    g.drawImage(wash, 0, 0, w, h, dx, dy, dw, dh);\n  }".replace('dw, dh','w, h').replace("dw = w * sc, dh = h * sc;\n    if (!tc) { g.drawImage(im, sx, 0, w, h, dx, dy, dw, dh); return; }",""), "PLACEHOLDER");
})();
