/* Music player: one looping track at a time with a short crossfade and a volume setting.
 * Tracks come from assets/music.js (generated by tools/music/compose.py). Audio starts after the first click, key or pad press (browser rule).
 * game.js calls BibooMusic.want(id) every frame; asking for the track that already plays does nothing. */
(function (root) {
  'use strict';
  const M = { volume: 0.6, current: null, wanted: null, ctx: null, ready: false };
  const KEY = 'pp_music_vol', STEPS = [0, 0.3, 0.6, 1];
  try { const v = parseFloat(root.localStorage.getItem(KEY)); if (STEPS.includes(v)) M.volume = v; } catch (e) {}
  const cfg = () => root.BIBOO && root.BIBOO.music;
  const ext = (() => { try { return document.createElement('audio').canPlayType('audio/ogg; codecs="vorbis"') ? 'ogg' : 'mp3'; } catch (e) { return 'mp3'; } })();
  const buffers = {}, loading = {}, failedAt = {}, local = root.location && root.location.protocol === 'file:';   // browsers refuse fetch() on file:// pages, so the music stays silent there
  let master = null, node = null;          // node: { id, src, gain }
  function ensure() {
    if (M.ctx) return M.ctx;
    const AC = root.AudioContext || root.webkitAudioContext; if (!AC) return null;
    try { M.ctx = new AC(); master = M.ctx.createGain(); master.gain.value = M.volume * 0.5; master.connect(M.ctx.destination); } catch (e) { M.ctx = null; }
    return M.ctx;
  }
  function load(id) {
    if (buffers[id]) return Promise.resolve(buffers[id]);
    if (loading[id]) return loading[id];
    const c = cfg(); if (local || !c || !(id in c.tracks) || !M.ctx || Date.now() - (failedAt[id] || 0) < 8000) return Promise.resolve(null);
    loading[id] = fetch(c.dir + id + '.' + ext).then(r => r.arrayBuffer()).then(ab => new Promise((ok, no) => M.ctx.decodeAudioData(ab, ok, no)))
      .then(b => (buffers[id] = b)).catch(() => { delete loading[id]; failedAt[id] = Date.now(); return null; });
    return loading[id];
  }
  function start(id) {
    const ctx = M.ctx; if (!ctx || M.current === id) return;
    load(id).then(buf => {
      if (!buf || M.wanted !== id || M.current === id) return;
      const now = ctx.currentTime, gain = ctx.createGain(), src = ctx.createBufferSource();
      src.buffer = buf; src.loop = true; gain.gain.setValueAtTime(0, now); gain.gain.linearRampToValueAtTime(1, now + 0.5);
      src.connect(gain); gain.connect(master); src.start(0);
      if (node) { const old = node; old.gain.gain.cancelScheduledValues(now); old.gain.gain.setValueAtTime(old.gain.gain.value, now); old.gain.gain.linearRampToValueAtTime(0, now + 0.5); setTimeout(() => { try { old.src.stop(); old.src.disconnect(); old.gain.disconnect(); } catch (e) {} }, 650); }
      node = { id, src, gain }; M.current = id;
    });
  }
  function stopAll() {
    if (node && M.ctx) { const old = node, now = M.ctx.currentTime; old.gain.gain.setValueAtTime(old.gain.gain.value, now); old.gain.gain.linearRampToValueAtTime(0, now + 0.5); setTimeout(() => { try { old.src.stop(); } catch (e) {} }, 650); }
    node = null; M.current = null;
  }
  M.want = function (id) {
    if (id === M.wanted) return;
    M.wanted = id;
    if (!id) { stopAll(); return; }
    if (M.ready && M.volume > 0) start(id);
  };
  M.setVolume = function (v) {
    M.volume = v; try { root.localStorage.setItem(KEY, String(v)); } catch (e) {}
    if (master) master.gain.value = v * 0.5;
    if (v > 0 && M.ready && M.wanted && !M.current) start(M.wanted);
  };
  M.cycle = function () { const i = STEPS.indexOf(M.volume); M.setVolume(STEPS[(i + 1) % STEPS.length]); return M.volume; };
  M.label = () => M.volume === 0 ? 'Off' : Math.round(M.volume * 100) + '%';
  function unlock() {
    const ctx = ensure(); if (!ctx) return;
    const go = () => { M.ready = true; if (M.wanted && M.volume > 0) start(M.wanted); };
    if (ctx.state === 'suspended') ctx.resume().then(go, go); else go();
  }
  ['pointerdown', 'keydown', 'touchstart'].forEach(e => root.addEventListener(e, unlock, { passive: true }));
  root.addEventListener('gamepadconnected', unlock);
  M.pollPad = () => { if (M.ready) return; try { for (const p of (navigator.getGamepads ? navigator.getGamepads() : [])) if (p && p.buttons.some(b => b.pressed)) { unlock(); return; } } catch (e) {} };
  root.BibooMusic = M;
})(window);
